sonar.projectKey=distributed-log-monitoring
sonar.projectName=distributed-log-monitoring
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/.venv/**,**/.next/**,monitoring/loki-storage/**
sonar.python.version=3.11
sonar.javascript.lcov.reportPaths=coverage/lcov.info
